### ISSUE TITLE
SlackMemoListで削除を選択するとキャンセルできない。

### ISSUE THREAD

**Issue by vintersnow** [tsuyoshiwada/slack-memo-vim#1]
SlackMemoListで出した一覧で`d`を押すと本当に削除するか聞かれますが、`N`を押しても削除されてしまいます。
その他`esc`でも削除されます。

neovim 0.1.7
macOS 10.11.6

**Comment by wadackel** [comment]
Issue ありがとうございます 😃 
確かにご指摘いだきましたバグ確認しました。

今夜〜明日辺りに修正しようと思います。

**Comment by wadackel** [comment]
遅くなってしまいましたが, 削除時のバグ修正しました :pray:

**Comment by vintersnow** [comment]
いえいえ、素早い対応ありがとうございます！

**Comment by wadackel** [comment]
とんでもないです, 他にも何かあればまたよろしくお願いしまーす !
